plugins:
  - "@dotcom-tool-kit/component"
  - "./toolkit/karma"
  
hooks:
  test:local:
    - KarmaLocal
  test:ci:
    - KarmaCI

options:
  "@dotcom-tool-kit/circleci":
    nodeVersion:
      - '18.20-browsers'
